= Developing on SKALE

== Start Building on Testnet

SKALE Testnet has now been updated to v3 on Holesky. New chains are available and Chaos has been deprecated.

To get started, follow the steps below:

1. Please visit https://testnet.portal.skale.space/chains
2. Select your chain:
  * Nebula for Gaming
  * Europa for DeFi
  * Titan for AI & ML
  * Calypso for everything else
3. Visit the https://sfuelstation.com[sFUEL Station], and work through the prompts
4. Select the button "Click for Testnet"
5. Select "Claim sFUEL" on the same chain you selected above
6. Begin deploying contracts with your favorites tools!

== Existing dApps

You can deploy your contracts over to your SKALE Chain and begin to use faster and zero-cost gas transactions. Depending on your architecture and needs, you may want to evaluate which contracts to keep on Ethereum and which to serve on SKALE, such as putting more end-user facing transactions on SKALE and transactions requiring PoW security on Ethereum.

[NOTE]
SKALE Chains have unique access control features. New SKALE Chains only permit the SKALE Chain owner the ability to deploy contracts. See xref:skale-chain-administration::skale-chain-access-control.adoc[SKALE Chain Access Control] for more information.

For using the Ethereum-SKALE bridge called Interchain Messaging Agent, you can customize your own bridge and map tokens you select to support, or enable automatic mapping.

To enable existing contracts to interact with the messaging layer, you'll have to add an interface to communicate with the IMA MessageProxy layer. 

Already have an ERC-721 on Mainnet? You can use the IMA extension contracts to enable any new tokens minted on SKALE to be minted on Ethereum while preserving the URI and original Minter address on mainnet. 

== New dApps

Whether starting a new project or migrating from another EVM Chain, checkout some of the tools and resources below or head over to the xref:recipes::index.adoc[Recipes] and start deploying smart contracts in minutes. 

== Developer Tool Docs

* https://hardhat.org/hardhat-runner/docs/getting-started[Hardhat Docs]
* https://remix-ide.readthedocs.io/en/latest/#[Remix Docs]
* https://docs.openzeppelin.com[OpenZeppelin Docs]

== Basics of dapp Development

* https://cryptozombies.io[CryptoZombies]
* https://solidity-by-example.org[Solidity By Example]
* https://docs.soliditylang.org[Solidity Docs] and see https://docs.soliditylang.org/en/v0.8.6/#translations[Solidity Docs translations]
* https://ethereum.org/en/developers[Ethereum Developer Resources]

== Best Practices

* https://consensys.github.io/smart-contract-best-practices[Ethereum Smart Contract Security Best Practices]
* https://consensys.net/diligence/blog/2020/11/token-interaction-checklist[ConsenSys Diligence's Token Interaction Checklist]
